### ISSUE TITLE
Move templates to src

### ISSUE THREAD

**Issue by jamesrwilliams** [Fusion-Design/ee-boilerplate#3]
Write gulp task for copying templates from `/src/` to `/dist/` for local repos during production usage. Copying into these paths:
```
/src/templates => /dist/app/templates/default_site/
```

**Comment by jamesrwilliams** [comment]
Added new util:* task group. E.g. for templates: `$ gulp util:templates`. This is used by the init task and can be called independently to update template files. Also setup in watch task for any changes to the templates updates the dist ones.

**Would it be better to only move the changes when you run the command?**

**Comment by petefusion** [comment]
No I think it definitely needs to run any time changes are made to the 
source templates.
