### ISSUE TITLE
Rework gulp init into 2 step command

### ISSUE THREAD

**Issue by peteheaney** [Fusion-Design/ee-boilerplate#7]
Slight complication... turns out the config.php file needs to be empty in order for the installation wizard to run.

So we might need to look at a two stage gulp init as we discussed before, where the config.php file is updated post installation.

**Comment by jamesrwilliams** [comment]
So ideally we capture some information during setup (gulp init) and then change the config file after the EE wizard? What would we need to collect:

- EE version number
- Admin email

**Comment by peteheaney** [comment]
- Account name
- Encryption key?

I think that's everything that would need to be changed in the config file.

We'll also need to document a workflow for this in the boilerplate readme.  The installation wizard will be run on the server, so after the config file has been changed, it will need to be uploaded to the server.

**Comment by jamesrwilliams** [comment]
Maybe we could setup our own config.json type file. With all this information in it that it would then use post gulp init. 

Does changing the config.php file in production do any harm, say you wanted to change the admin email mid-production?

If not the post gulp init command could be a utility for updating the site files in general.

**Comment by peteheaney** [comment]
Yeah that sounds like it could be good.  Updating config.php in production won't break anything.  Well, depending on what you change.

**Comment by jamesrwilliams** [comment]
Now most important part of this entire process. What do we call this new task?

1. `gulp init`
2. 
3. Profit?

**Comment by petefusion** [comment]
gulp config
gulp setup
gulp finish

Or we could have init-pre and init-post.

Don't know, I'm struggling. Might need to sleep on this one.

**Comment by jamesrwilliams** [comment]
Okay so breakdown of what each task does is like the following:

## 1. gulp config

All tasks relating to pre-wizard use.

- Moving system folder above public_html
- Move the uploads folder from images
- Remame images to assets

## 2. gulp setup

Tasks relating to post-wizard use.

- Move config.php
- Change $system_path from `./system/` => `../system/`

## 3. gulp finish

- ?

## utl:update

Not part of setup but that reusable config task that grabs setup details from user and/or custom config json file and write js/css doc headers with things like: EE version number, Admin email, Account name (for the path variable) Encryption key

**Comment by petefusion** [comment]
Do we need three tasks?  Changing $system_path needs to go in the first 
task, beacause that goes hand in hand with moving the system folder 
above public_html.

Basically, the only thing that needs to happen after the install wizard 
is updating the contents of config.php.
