### ISSUE TITLE
Bootstrap Intergration

### ISSUE THREAD

**Issue by jamesrwilliams** [Fusion-Design/ee-boilerplate#8]
Update on what I'm going to do with this. Moving to use bootstrap as our main SCSS setup with a vendor folder that globs and is combined with the base `bootstrap.scss` file. All bootstrap components are kept in the their respective folders.

**Comment by jamesrwilliams** [comment]
@peteheaney Managed to get it to glob imports but requires the file extension to be scss not css.

As css is valid scss there is no harm done just renaming the vendor css files when they're in the folder. Not ideal "drop and go" solution but will suffice for now?

**Comment by petefusion** [comment]
Yep, that'll do for now.

**Comment by jamesrwilliams** [comment]
I have now broken the `$ gulp js` task into two subtasks. First compiles all js files in the src/js/ folder into a single minifed file. Second copies all the .js files into the vendor js folder in dist.

I think this is a better choice to avoid namespace collisions with JS files?
